// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwDTIwf9LArJeUeW95d0JuN6Vlax1auHI',
    appId: '1:657702521010:web:fa953fdeaa9221b7a861ab',
    messagingSenderId: '657702521010',
    projectId: 'hotwheels-col-app',
    authDomain: 'hotwheels-col-app.firebaseapp.com',
    storageBucket: 'hotwheels-col-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvS8KpnwHsbO_DBNB2kwBoFJocz0HnZ8w',
    appId: '1:657702521010:android:139001432b8aedd3a861ab',
    messagingSenderId: '657702521010',
    projectId: 'hotwheels-col-app',
    storageBucket: 'hotwheels-col-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmeDcS02Ku_MZizorq86iU32ZHKzrYwss',
    appId: '1:657702521010:ios:792de5cf1dbb2d5aa861ab',
    messagingSenderId: '657702521010',
    projectId: 'hotwheels-col-app',
    storageBucket: 'hotwheels-col-app.firebasestorage.app',
    iosBundleId: 'com.hotwheels.hotwheelsApp',
  );
}
